package assets

var Quotes = []string{
	"“Victory belongs to the most persevering.\"",
	"“Success is the most convincing talker in the world.\"",
	"“It is only by prudence, wisdom, and dexterity, that great ends are attained and obstacles overcome. Without these qualities nothing succeeds.\"",
	"“Ten people who speak make more noise than ten thousand who are silent.\"",
	"“Courage isn’t having the strength to go on – it is going on when you don’t have strength.\"",
	"“If you want a thing done well, do it yourself.\"",
	"“I have seen in the most significant of circumstances, that some little thing always decides great events.\"",
	"“It’s the unconquerable soul of man, and not the nature of the weapon he uses, that ensures victory.\"",
	"“Throw off your worries when you throw off your clothes at night.\"",
	"“History is written by the winners.\"",
	"“The truest wisdom is a resolute determination.\"",
	"“Until you spread your wings, you’ll have no idea how far you can fly.\"",
	"“Success is the most convincing talker in the world.\"",
	"“The world suffers a lot. Not because the violence of bad people. But because of the silence of the good people.\"",
	"“Imagination governs the world.\"",
	"“Ability is of little account without opportunity.\"",
	"“We are made weak both by idleness and distrust of ourselves. Unfortunate, indeed, is he who suffers from both. If he is a mere individual he becomes nothing; if he is a king he is lost.\"",
	"“A leader is a dealer in hope.\"",
	"“One must change one’s tactics every ten years if one wishes to maintain one’s superiority.\"",
	"“The greater the man, the less is he opinionative, he depends upon events and circumstances.\"",
	"“There is one kind of robber whom the law does not strike at, and who steals what is most precious to men: time.\"",
	"“The best cure for the body is a quiet mind.\"",
	"“There are but two powers in the world, the sword and the mind. In the long run the sword is always beaten by the mind.\"",
	"“Men take only their needs into consideration – never their abilities.\"",
	"“Nothing is more difficult, and therefore more precious, than to be able to decide.\"",
	"“Take time to deliberate, but when the time for action comes, stop thinking and go in.\"",
	"“The reason most people fail instead of succeed is they trade what they want most for what they want at the moment.\"",
	"“Death is nothing, but to live defeated and inglorious is to die daily.\"",
	"“As a rule it is circumstances that make men.\"",
	"“Courage cannot be counterfeited. It is one virtue that escapes hypocrisy.\"",
	"“Space I can recover. Time, never.\"",
	"“Religion is excellent stuff for keeping common people quiet. Religion is what keeps the poor from murdering the rich.\"",
	"“Let France have good mothers, and she will have good sons.\"",
	"“The future destiny of a child is always the work of the mother.\"",
	"“One should never forbid what one lacks the power to prevent.\"",
	"“The surest way to remain poor is to be an honest man.\"",
	"“The great proof of madness is the disproportion of one’s designs to one’s means.\"",
	"“True character stands the test of emergencies. Do not be mistaken, it is weakness from which the awakening is rude.\"",
	"“The French complain of everything, and always.\"",
	"“Show me a family of readers, and I will show you the people who move the world.\"",
	"“A woman laughing is a woman conquered.\"",
	"“The poor man and the beggar are two quite different classes: one commands respect, the other arouses anger.\"",
	"“Friends must always be treated as if one day they might be enemies.\"",
	"“It is the cause, not the death, that makes the martyr.\"",
	"“The hand that gives is among the hand that takes. Money has no fatherland, financiers are without patriotism and without decency, their sole object is gain.\"",
	"“Courage is like love, it must have hope for nourishment.\"",
	"“Four hostile newspapers are more to be feared than a thousand bayonets.\"",
	"“Ordinarily men exercise their memory much more than their judgment.\"",
	"“I know he’s a good general, but is he lucky?\"",
	"“I am surrounded by priests who repeat incessantly that their kingdom is not of this world, and yet they lay hands on everything they can get.\"",
	"“It is astonishing what power words have over men.\"",
	"“The fool has one great advantage over a man of sense — he is always satisfied with himself.\"",
	"“History is the version of past events that people have decided to agree upon.\"",
	"“Men are Moved by two levers only: fear and self-interest.\"",
	"“To understand the man you have to know what was happening in the world when he was twenty.\"",
	"“Greatness is nothing unless it be lasting.\"",
	"“You medical people will have more lives to answer for in the other world than even we generals.\"",
	"“If we could read the past histories of all our enemies we would disregard all hostility for them.\"",
	"“There is no such thing as accident; it is fate misnamed.\"",
	"“Men are more easily governed through their vices than through their virtues.\"",
	"“It requires more courage to suffer than to die.\"",
	"“Let the path be open to talent.\"",
	"“He who knows how to flatter also knows how to slander.\"",
	"“One must learn to forgive and not to hold a hostile, bitter attitude of mind, which offends those about us and prevents us from enjoying ourselves; one must recognize human shortcomings and adjust himself to them rather than to be constantly finding fault with them.\"",
	"“If you wish to be a success in the world, promise everything, deliver nothing.\"",
	"“It is a mistake, too, to say that the face is the mirror of the soul. The truth is, men are very hard to know, and yet, not to be deceived, we must judge them by their present actions, but for the present only.\"",
	"“The people to fear are not those who disagree with you, but those who disagree with you and are too cowardly to let you know.\"",
	"“There is no place in a fanatic’s head where reason can enter.\"",
	"“With audacity one can undertake anything, but not do everything.\"",
	"“All great events hang by a single thread. The clever man takes advantage of everything, neglects nothing that may give him some added opportunity; the less clever man, by neglecting one thing, sometimes misses everything.\"",
	"“You can ask me for anything you like, except time.\"",
	"“The strong man is the one who is able to intercept at will the communication between the senses and the mind.\"",
	"“Impossible is the word found only in a fool’s dictionary. Wise people create opportunities for themselves and make everything possible…\"",
	"“Men will risk their lives, even die for ribbons.\"",
	"“It is my wish that my ashes may repose on the banks of the Seine, in the midst of the French people, whom I have loved so well.\"",
	"“A man will fight harder for his interests than for his rights.\"",
	"“At twenty-two many things are allowed which are no longer permitted past thirty.\"",
	"“In order to govern, the question is not to follow out a more or less valid theory but to build with whatever materials are at hand. The inevitable must be accepted and turned to advantage.\"",
	"“What is history but a fable agreed upon?”",
}